POST http://localhost:3000/accounts
x-signature: {{$dotenv SIGNATURE}}
content-type: application/json

{
	"code":"",
		"integration": {
		"controlidOnPremise" : {
			"accessControlByLimit": false,
			"automatedCheckIn": true,
			"genQrCode": true,
			"userRegistration": true,
			"inHomologation": true,
			"mailsInHomologation": [],
			"deskbeeExcludedGroups": [], 
			"mailsExcluded": [],
			"activePlaces": [],
			"database":{
				"mysql": {
					"host": "localhost",
					"username": "root",
					"password": "P4sswD",
					"port": 3307,
					"database": "acesso"
				}
				//sql: {path: "C:\\ProgramData\\Control iD\\iDSecure\\acesso.sqlite"}
			}, 
			"api":{
				"host": "localhos:30443/api",
					"user": "admin",
					"password": "admin"
			}
			
			
		}
	}
}