POST http://localhost:3000/accounts
x-signature: {{$dotenv SIGNATURE}}
content-type: application/json

{
		"integration": {
		"controlidOnPremise" : {
			"accessControlByLimit": false,
			"automatedCheckIn": false,
			"genQrCode": false,
			"userRegistration": false,
			"inHomologation": true,
			"mailsInHomologation": [],
			"deskbeeExcludedGroups": [], 
			"mailsExcluded": [],
			"activePlaces": [],
			"database":{
				"mysql": {
					"host": "localhost",
					"username": "root",
					"password": "P4sswD",
					"port": 3307,
					"database": "acesso"
				}
				//"sqlite": {"path": "C:\\ProgramData\\Control iD\\iDSecure\\acesso.sqlite"}
			}, 
			"api":{
				"host": "https://localhost:30443/api",
					"user": "admin",
					"password": "admin"
			}
			
			
		}
	}
}